#cloud-config
timezone: Europe/Amsterdam
locale: en_US.UTF-8

ntp:
  enabled: true

users:
  - name: system
    passwd: "$6$Ke1kyibTI$3QN3.KijfpJxklZWSS6ONcg9gtvw1hWe9qxsB9.RqSDEd2q4JEY9GtDGyfdOFJ6EBWaM9kWqURyhJxlNCEKsy/"
    shell: /bin/bash
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_authorized_keys:
     - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFM0iEBuZCiOXBON8eJButuRzyxdTaKHRwngXRO0Y5QIfINiM4qlK0NOo5YSlNuoR2i4A7R9aq/j++RHb84vYIS9QDztV2zJl4Z4tjSF11EOvLPt7Vq7kMfc3x3Wh7GrszNsSNc+u4MD1ZZNJ0h/YNk/Hi2SLWhvsJdFHYJGhli03A/SA== dave@ares
     - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGHSUPSrpC0od7iCatOMeXv1HjSWhZVGaVPf0J+ycHsUfKlHUBsV2P9ld4jHRddZx0ik4ROs0i5oEtoKEmUcJlMYwHJD7M6E3jlv/3AK2NcROeNponVLap18eqCtX4QhdrcigV/+JJz+TRMckPXsxDlrw2gJFyGC8aOXRYif0f3jdEAGA== dave@artemis

apt:
  # keep existing sources (cloud-init wipes them by default)
  preserve_sources_list: true

# add each entry to ~/.ssh/authorized_keys for the configured user or the
# first user defined in the user definition directive.
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJ5HlTMLWfPBnv9dC0LBqzFtk0r2OBu9UfHdsbMR5YExSQHnhCI5yNrCDbhxDa/Xd/2x3LYYtcI+VW5Li7inO71wNxrMys9/obAVOXXVgPzOLX/5uG2HNlY1mN9qqhjToZSVTFhJBB3gMLDbuIkI81JrKGWAFFj6nakVdhVXHV3V5hclgQhlFLDmUhmINw9Tk9UkdCn9cWbOIaJmaVtJhDk2rxoqlz/SEaUKzN6RctgmrSggpVNEkAWAWvzoo1b6rkLv14QR2uu02FPpGx0dnicAP/VZGwiTDA0P/XVCa088m4v7MNODG3iWLr8oo4o0Syj5pHaYI60ji/wt2V1ogQGQrkJot/3TWc81z1Pz5YAKhOgnql2WBCJCWGAr81q+pJpMOitCaa5mP8uFHmUsVpYTI3clhy81shmgWyVEgsnLpARKK1rXzIhtYeoHlK60UlP1zwN+caAvE5LJFvJYyQsu73TNhBCyW8MHeOpwiofBF42tCgC4gF/PsNEspc+9sKYiVfIfFdFbgLRsvk7GZS4IDUcOqA8Z68uhECi5Qxemzf6cQerK9jrpZalq57JG/kuXHZfvg65xUbQv5MuI0OdvzuRphK04C1RU+C5VW3hQQmUwdzQ912KNwvY+TTsTzTEjgPU1i8RkF6Jd2fCC6ZeAoYKwfSffFh0MmPCiq+Tw== pndurette@gmail.com

package_upgrade: true
packages:
  - htop
  - vim