---
- include_tasks: install.yml
  tags:
    - drbd

- include_tasks: disks.yml
  tags:
    - drbd
    - drbd-config
    - drbd-disks

- include_tasks: heartbeat.yml
  tags:
    - drbd
    - drbd-heartbeat
  when: "'heartbeat_cluster' in group_names"

- include_tasks: config.yml
  tags:
    - drbd
    - drbd-config

- include_tasks: services.yml
  tags:
    - drbd
    - drbd-services
