---
- name: Ensuring drbd Service Is Enabled On Boot
  service:
    name: drbd
    enabled: true
  become: true

- name: Ensuring heartbeat Service Is Enabled On Boot
  service:
    name: heartbeat
    enabled: true
  become: true
