---
- name: Perform full upgrade
  hosts: homelab-packer
  gather_facts: no
  become: yes
  tasks:
  - name: Do upgrade
    apt:
      update_cache: yes
      upgrade: dist
    register: upgrade
  # https://github.com/ansible/ansible/issues/26521#issuecomment-371142617
  - name: Remove nondownloadable packages from cache
    apt:
      autoclean: yes
    when: upgrade is succeeded
  - name: Remove and purge orphaned packages
    apt:
      autoremove: yes
      purge: yes
    when: upgrade is succeeded
