---
- name: Create TLS agent CA cert
  no_log: true
  ansible.builtin.copy:
    content: "{{ consul_tls_agent_ca_cert }}"
    dest: "{{ consul_agent_ca_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

- name: Create TLS key
  no_log: true
  ansible.builtin.copy:
    content: "{{ consul_tls_key }}"
    dest: "{{ consul_key_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

- name: Create TLS cert
  no_log: true
  ansible.builtin.copy:
    content: "{{ consul_tls_cert }}"
    dest: "{{ consul_cert_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

# - name: Create ACL policy configuration
#   ansible.builtin.template:
#     src: configd_50acl_policy.json.j2
#     dest: "{{ consul_configd_directory }}/50acl_policy.json"
#     owner: "{{ consul_user }}"
#     group: "{{ consul_group }}"
#     mode: "0600"
#   notify:
#     - restart consul
