---
- name: ACL policy configuration
  template:
    src: acl_policy.hcl.j2
    dest: "{{ consul_config_path }}/{{ item }}/acl_policy.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group}}"
  with_items:
    - bootstrap
    - client
    - server
  notify:
    - restart consul