---
- name: Creating Consul group
  ansible.builtin.group:
    name: "{{ consul_group }}"
    system: true

- name: Creating Consul user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    home: "{{ consul_config_directory }}"
    group: "{{ consul_group }}"
    shell: /sbin/nologin
    system: true

- name: Creating Consul directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0750"
  with_items:
    - "{{ consul_config_directory }}"
    - "{{ consul_data_directory }}"
