---
- name: Creating Consul group
  ansible.builtin.group:
    name: "{{ consul_group }}"
    system: true
  register: consul_group_created

- name: Creating Consul user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    home: "{{ consul_config_directory }}"
    group: "{{ consul_group }}"
    shell: /sbin/nologin
    system: true
  when: consul_group_created.changed

- name: Ensure Consul is installed
  block:
    - name: Test Consul
      ansible.builtin.command: consul --version
      register: consul_version_test
      changed_when: false

    - name: Test if correct version is installed
      ansible.builtin.assert:
        that:
          - consul_version in consul_version_test.stdout
        success_msg: "Consul version {{ consul_version }} is installed"
        fail_msg: Consul was not successfully installed
  rescue:
    - name: Ensure old consul is removed
      ansible.builtin.file:
        path: "{{ consul_install_directory }}/consul"
        state: absent

    - debug:
        var: consul_download

    - name: Install Consul
      ansible.builtin.unarchive:
        src: "{{ consul_download }}"
        dest: "{{ consul_install_directory }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        remote_src: true
        mode: "0755"

- name: Creating Consul directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: directory
    mode: "0750"
  with_items:
    - "{{ consul_config_directory }}"
    - "{{ consul_data_directory }}"
    - "{{ consul_cert_directory }}"

- name: Check for consul log directory
  ansible.builtin.stat:
    path: "{{ consul_log_file|dirname }}"
  register: consul_log_dir

- name: Create log directory if not exists
  ansible.builtin.file:
    path: "{{ consul_log_file|dirname }}"
    owner: root
    group: root
    state: directory
  when: not consul_log_dir.stat.exists

- name: Pre-create log file
  ansible.builtin.file:
    path: "{{ consul_log_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: touch
  changed_when: false

- name: Create TLS agent CA cert
  no_log: True
  ansible.builtin.copy:
    content: "{{ consul_tls_agent_ca_cert }}"
    dest: "{{ consul_agent_ca_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

- name: Create TLS key
  no_log: True
  ansible.builtin.copy:
    content: "{{ consul_tls_key }}"
    dest: "{{ consul_key_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

- name: Create TLS cert
  no_log: True
  ansible.builtin.copy:
    content: "{{ consul_tls_cert }}"
    dest: "{{ consul_cert_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0600"
  notify:
    - restart consul

- name: templating out consul configuration
  template:
    src: consul.hcl.j2
    dest: "{{ consul_config_directory }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"

- name: templating out consul server configuration
  template:
    src: server.hcl.j2
    dest: "{{ consul_server_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  when: "'consul_server' in group_names"