---
- name: Ensure Consul is installed
  block:
    - name: Test Consul
      ansible.builtin.command: consul --version
      register: consul_version_test
      changed_when: false

    - name: Test if correct version is installed
      ansible.builtin.assert:
        that:
          - consul_version in consul_version_test.stdout
        success_msg: "Consul version {{ consul_version }} is installed"
        fail_msg: Consul was not successfully installed
  rescue:
    - name: Ensure old consul is removed
      ansible.builtin.file:
        path: "{{ consul_install_directory }}/consul"
        state: absent

    - name: Install Consul
      ansible.builtin.unarchive:
        src: "{{ consul_download }}"
        dest: "{{ consul_install_directory }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        remote_src: true
        mode: "0755"

- name: Creating Consul directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: directory
    mode: "0750"
  with_items:
    - "{{ consul_config_directory }}"
    - "{{ consul_configd_directory }}"
    - "{{ consul_data_directory }}"
    - "{{ consul_cert_directory }}"

- name: Check for consul log directory
  ansible.builtin.stat:
    path: "{{ consul_log_file | dirname }}"
  register: consul_log_dir

- name: Create log directory if not exists
  ansible.builtin.file:
    path: "{{ consul_log_file | dirname }}"
    owner: root
    group: root
    state: directory
    mode: "0700"
  when: not consul_log_dir.stat.exists

- name: Pre-create log file
  ansible.builtin.file:
    path: "{{ consul_log_file }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: touch
    mode: "0750"
  changed_when: false

- name: Create configuration
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: "{{ consul_config_directory }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify:
    - restart consul

- name: Create server configuration
  ansible.builtin.template:
    src: server.hcl.j2
    dest: "{{ consul_config_directory }}/server.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: "0640"
  notify:
    - restart consul
