---
- name: Ensure Consul is installed
  block:
    - name: Test Consul
      ansible.builtin.command: consul --version
      register: consul_version_test
      changed_when: false

    - name: Test if correct version is installed
      ansible.builtin.assert:
        that:
          - consul_version in consul_version_test.stdout
        success_msg: "Consul version {{ consul_version }} is installed"
        fail_msg: Consul was not successfully installed
  rescue:
    - name: Ensure old consul is removed
      ansible.builtin.file:
        path: "{{ consul_install_directory }}/consul"
        state: absent

    - name: Install Consul
      ansible.builtin.unarchive:
        src: "{{ consul_download }}"
        dest: "{{ consul_install_directory }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        remote_src: true
        mode: "0755"
