---
- name: Install Consul
  ansible.builtin.include_tasks: ./install.yml

- name: Configure ACL
  ansible.builtin.include_tasks: ./acl.yml

- name: Setup service
  ansible.builtin.include_tasks: ./service.yml
# - name: Setup service
#   ansible.builtin.include_tasks: ./service.yml

# - name: Setup dnsmasq
#   ansible.builtin.include_tasks: ./dnsmasq.yml
