VAGRANTFILE_API_VERSION = "2"

base_dir = File.expand_path(File.dirname(__FILE__))
cluster = {
  "node1" => { :ip => "192.168.56.11",  :cpus => 1, :mem => 1024 },
  "node2" => { :ip => "192.168.56.12", :cpus => 1, :mem => 1024 },
  "node3" => { :ip => "192.168.56.13", :cpus => 1, :mem => 1024 },
}
vm_box = "debian/bullseye64"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.enable :apt
  end

  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|

      cfg.ssh.insert_key = false

      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = vm_box
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname

        vb.name = 'vagrant-mesos-' + hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on" ]
      end

      # provision nodes with ansible
      if index == cluster.size - 1
        cfg.vm.provision :ansible do |ansible|
          # ansible.verbose = "vvvv"

          ansible.config_file = './ansible.cfg'
          ansible.inventory_path = 'inventory/hosts'
          ansible.playbook = './../ansible/playbooks/bootstrap.yml'
          ansible.limit = 'all'# "#{info[:ip]}" # Ansible hosts are identified by ip
        end # end provision
      end #end if

    end # end config

  end #end cluster

end #end vagrant