base_dir = File.expand_path(File.dirname(__FILE__))
cluster = {
  "node1" => { :ip => "192.168.56.11", :cpus => 1, :mem => 1024 },
  "node2" => { :ip => "192.168.56.12", :cpus => 1, :mem => 1024 },
  "node3" => { :ip => "192.168.56.13", :cpus => 1, :mem => 1024 },
}
vm_box = "debian/bookworm64"

# required_plugins = %w(vagrant-share vagrant-vbguest vagrant-libvirt vagrant-cachier)
required_plugins = %w(vagrant-share vagrant-cachier)

Vagrant.configure("2") do |config|

  plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
  if not plugins_to_install.empty?
    puts "Installing plugins: #{plugins_to_install.join(' ')}"
    if system "vagrant plugin install #{plugins_to_install.join(' ')}"
      exec "vagrant #{ARGV.join(' ')}"
    else
      abort "Installation of one or more plugins has failed. Aborting."
    end
  end

  config.cache.scope = :machine
  config.cache.enable :apt

  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|

      cfg.ssh.insert_key = false
      cfg.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "_keys/id_rsa"]

      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = vm_box
        override.vm.network :private_network, ip: "#{info[:ip]}"

        vb.name = 'vagrant-' + hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on" ]

        # Create a second disk (2G)
        disk = "storage-disk-#{hostname}.vdi"
        unless File.exist? (disk)
          vb.customize ['createhd', '--filename', disk, '--size', 2 * 1024]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type',  'hdd', '--medium', disk]
      end

      # provision nodes with ansible
      if index == cluster.size - 1
        cfg.vm.provision :ansible do |ansible|
          # ansible.verbose = "vvvv"

          ansible.config_file = "./ansible.cfg"
          ansible.inventory_path = "inventory/hosts"
          ansible.playbook = "./playbook.yml"
          ansible.limit = "all"# "#{info[:ip]}" # Ansible hosts are identified by ip
          ansible.extra_vars = {
            ssh_public_keys: ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtaxksKXfCx2OK1cXe0QnNBI0XSWpQ+8l3PqLqJnVpU88XSm1n9VrVC49vblReY59k/djmliuSs0DStox/N5utPvWY4+5jw4xkhWZ+rdSTf0xXBg0QvGHK0QnoJTCeKR3bDTE8+1KnbDwiSmzc8LyzLI0HdmRsaVzNamLwVY19rF0iPP0qkG4PZ7ZSU1psravxGuMNUv9o7ykatb9lLhjgs0Wn3nzfOUupY7kT1eyOi6t0S/z1JBFgkwPx/5xe84cmR5FeShwCq+YuoMY6kc75u4el0JOvWHTADRju416e4fwfEpixDv2xJ6HR5R1Z7xsXuPB1TBikG7ZelnyAPCzGPGnyq4zZsVVLQKVXQlZXHfRrHvQm8eMX826Yv42QDjmzCDkdSpVFmzi2qbe7udTj0SzQX2nW52FeLhPgNum8yCX3nVHZiPeq1mrq8yt07AmBNvcFO7XAiEyUZMwtr71wvwXdnn2XvqX2WUTwLiLGDEv5lIAHaOEScTkn0HNO6pM= dave@ares"],
          }
        end # end provision
      end #end if

    end # end config

  end #end cluster

end #end vagrant
