---
drbd_deb_packages: 
  - drbd-utils

drbd_network_shared_secret: sJyX2JM5

drbd_common:
  disk: ''
  net: |
    protocol C;
    cram-hmac-alg sha1;
    shared-secret "{{ drbd_network_shared_secret }}";
  handlers: ''
  startup: |
    # wfc-timeout degr-wfc-timeout outdated-wfc-timeout
    # wait-after-sb;
    wfc-timeout 100;
    degr-wfc-timeout 120;
  options: ''

drbd_disks:
  - device: /dev/drbd0
    disk: /dev/sda
    filesystem: ext4
    partitions: 1
    mountpoint: /mnt/storage
    mountopts: defaults
    resource: r0
    state: present
    use_partition: /dev/sda1