---
drbd_deb_packages:
  - drbd-utils
  - heartbeat

drbd_network_shared_secret: sJyX2JM5

drbd_common:
  disk: ''
  net: |
    protocol C;
    cram-hmac-alg sha1;
    shared-secret "{{ drbd_network_shared_secret }}";
  handlers: ''
  startup: ''
  # startup: |
  #   # wfc-timeout degr-wfc-timeout outdated-wfc-timeout
  #   # wait-after-sb;
  #   wfc-timeout 100;
  #   degr-wfc-timeout 120;
  options: ''

drbd_disks:
  - device: /dev/drbd0
    disk: /dev/sda
    partitions: 1
    state: present
    resource: r0

drbd_vip: 192.168.2.220
drbd_unicast_port: 694

drbd_iface: eth0
