---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true

  roles:
    - name: Install Docker
      role: geerlingguy.docker
      vars:
        # install docker compose plugin instead of docker-compose binary
        docker_install_compose_plugin: true
        docker_install_compose: false
        docker_users: ["{{ user }}"]
