---
nomad_user: nomad
nomad_group: nomad

nomad_datacenter: "{{ datacenter_name }}"
nomad_region: global

nomad_configd_directory: /etc/nomad.d
nomad_data_directory: /var/lib/nomad
nomad_install_directory: /usr/bin

nomad_version: 1.7.2
nomad_architecture: "{{ architecture_map[ansible_architecture] }}"
nomad_archive: "nomad_{{ nomad_version }}_linux_{{ nomad_architecture }}.zip"
nomad_download: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/{{ nomad_archive }}"
nomad_run_path: /run/nomad

nomad_log_level: INFO
nomad_log_file: /var/log/nomad
nomad_log_rotate_bytes: 0
nomad_log_rotate_duration: 24h
nomad_log_rotate_max_files: 0

nomad_bind_address: "{{ ansible_default_ipv4.address  }}"
nomad_advertise_address: "{{ nomad_bind_address }}"

nomad_ports:
  http: 4646
  rpc: 4647
  serf: 4648
