#cloud-config
# The top level settings are used as module
# and system configuration.
datasource_list: [ NoCloud, None ]
datasource:
  NoCloud:
    seedfrom: /boot/

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
  - name: system
    gecos: system
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: true
    ssh_authorized_keys:
     - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFM0iEBuZCiOXBON8eJButuRzyxdTaKHRwngXRO0Y5QIfINiM4qlK0NOo5YSlNuoR2i4A7R9aq/j++RHb84vYIS9QDztV2zJl4Z4tjSF11EOvLPt7Vq7kMfc3x3Wh7GrszNsSNc+u4MD1ZZNJ0h/YNk/Hi2SLWhvsJdFHYJGhli03A/SA== dave@ares
     - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAGHSUPSrpC0od7iCatOMeXv1HjSWhZVGaVPf0J+ycHsUfKlHUBsV2P9ld4jHRddZx0ik4ROs0i5oEtoKEmUcJlMYwHJD7M6E3jlv/3AK2NcROeNponVLap18eqCtX4QhdrcigV/+JJz+TRMckPXsxDlrw2gJFyGC8aOXRYif0f3jdEAGA== dave@artemis
    password: $6$rounds=4096$9Ms2KsVWsO$qODrsJMJ8D5DX94LKfCIt28VZS..k4TH767Bq4otbqzDfcTaN85XdArQrViP8Y1A49pw4O20Q41Fq28cHgwIF/

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the above $user (debian)
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - bootcmd
 - write-files
 - mounts
 - rsyslog
 - set_hostname
 - update_hostname
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - ssh-import-id
 - locale
 - set-passwords
 - ntp
 - timezone
 - runcmd
 - apt-configure

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - phone-home
 - final-message

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
  # This will affect which distro class gets used
  distro: debian
  # Other config here will be given to the distro class and/or path classes
  paths:
    cloud_dir: /var/lib/cloud/
    templates_dir: /etc/cloud/templates/