---
- name: Creating Vault group
  ansible.builtin.group:
    name: "{{ vault_group }}"
    system: true

- name: Creating Vault user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    createhome: no
    group: "{{ vault_group }}"
    shell: /sbin/nologin
    system: true

- name: Creating Vault directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"
  with_items:
    - "{{ vault_config_directory }}"
    - "{{ vault_data_directory }}"
    - "{{ vault_tls_directory }}"

- name: Creating Vault plugin directory
  ansible.builtin.file:
    state: directory
    path: "{{ vault_plugin_directory }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0750"
