---
- name: Ensure Vault is installed
  block:
    - name: Test Vault
      ansible.builtin.command: vault --version
      register: vault_version_test
      changed_when: false

    - name: Test if correct version is installed
      ansible.builtin.assert:
        that:
          - vault_version in vault_version_test.stdout
        success_msg: "Vault version {{ vault_version }} is installed"
        fail_msg: Vault was not successfully installed
  rescue:
    - name: Ensure old vault is removed
      ansible.builtin.file:
        path: "{{ vault_install_directory }}/vault"
        state: absent

    - name: Install Vault
      ansible.builtin.unarchive:
        src: "{{ vault_download }}"
        dest: "{{ vault_install_directory }}"
        owner: "{{ vault_user }}"
        group: "{{ vault_group }}"
        remote_src: true
        mode: "0755"
