---
# - name: Configure Vault
#   ansible.builtin.include_tasks: ./config.yml

# - name: Install Vault
#   ansible.builtin.include_tasks: ./install.yml

- name: Configure CA
  ansible.builtin.include_tasks: ./ca.yml

- name: Start srvice
  ansible.builtin.include_tasks: ./service.yml