---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    filename: docker.list
    state: present
    update_cache: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: false

- name: Run and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

# - name: Install docker-compose
#   ansible.builtin.get_url:
#     url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture | lower }}"
#     dest: /usr/local/bin/docker-compose
#     mode: u+x,g+x

# - name: Change ownership of docker-compose to {{ ansible_user }}
#   ansible.builtin.file:
#     path: /usr/local/bin/docker-compose
#     owner: "{{ ansible_user }}"

# - name: Add {{ ansible_user }} to docker group
#   ansible.builtin.user:
#     name: "{{ ansible_user }}"
#     groups: docker
#     append: yes
