---
consul_user: consul
consul_group: consul

consul_datacenter: "{{ datacenter_name }}"

consul_config_directory: /etc/consul.d
consul_data_directory: /var/lib/consul
consul_install_directory: /usr/bin
consul_home_directory: /opt/consul
consul_cert_directory: "{{ consul_home_directory }}/cert"

consul_cert_file: "{{ consul_cert_directory }}/consul.crt"
consul_key_file: "{{ consul_cert_directory }}/consul.key"
consul_agent_ca_file: "{{ consul_cert_directory }}/ca.crt"

consul_log_file: /var/log/consul

consul_version: 1.17.0
consul_architecture: "{{ architecture_map[ansible_architecture] }}"
consul_archive: "consul_{{ consul_version }}_linux_{{ consul_architecture }}.zip"
consul_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_archive }}"

consul_gossip_key: PcHsUpryiSwYSWfH/7zVtI1OrTOIeXGSAE4wj/XOUNw=

consul_tls_min_version: TLSv1_3

consul_port_dns: 8600
consul_port_http: 8500
consul_port_https: -1
consul_port_grpc: -1
consul_port_serf_lan: 8301
consul_port_serf_wan: 8302
consul_port_server: 8300

consul_client_addr: 0.0.0.0
consul_advertise_addr: '{{ ansible_default_ipv4.address }}'

consul_raft_multiplier: 1


consul_dnsmasq:
  listen_interface:
    - lo
    - docker0
    - eth0
  no_dhcp_interface:
    - lo
    - docker0
    - eth0
  upstream_servers:
    - 1.1.1.1
    - 1.0.0.1
