---
consul_user: consul
consul_group: consul

consul_config_directory: /etc/consul.d
consul_data_directory: /var/lib/consul
consul_install_directory: /usr/bin

consul_config_file: "{{ consul_config_directory }}/consul.hcl"

consul_version: 1.9.5
consul_architecture: "{{ architecture_map[ansible_architecture] }}"
consul_archive: "consul_{{ consul_version }}_linux_{{ consul_architecture }}.zip"
consul_download: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ consul_archive }}"
