---
consul_version: 1.17.0
consul_webui_version: 1.3.0

consul_datacenter: "{{ datacenter_name }}"

consul_server: true
consul_webui: true

consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ arch[ansible_architecture] }}.zip"

arch:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
