#cloud-config
timezone: Europe/Amsterdam
locale: en_US.UTF-8

ntp:
  enabled: true

users:
  - system

apt:
  # keep existing sources (cloud-init wipes them by default)
  preserve_sources_list: true

# package_upgrade: true
packages:
  - htop
  - vim